# Generated by Django 4.0.2 on 2022-03-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='lender',
        ),
    ]
